### ISSUE TITLE
1.2.15 - angular.d.ts references jquery/jquery.d.ts

### ISSUE THREAD

**Issue by ymoran00** [dt-bower/dt-angular#4]
... instead dt-jquery.d.ts

**Comment by eggers** [comment]
+1 The current dt-angular distribution is broken because of this issue.

**Comment by ThatRendle** [comment]
Sorry, I'll do something about that.

On Wednesday, 2 April 2014, eggers notifications@github.com wrote:

> +1 The current dt-angular distribution is broken because of this issue.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/dt-bower/dt-angular/issues/4#issuecomment-39279877
> .

## 

_Mark Rendle_
_Founder & CEO_
_Oort Corporation_
_Makers of_ _Zudio_ https://zud.io/

**Comment by DamianEdwards** [comment]
+1 this is quite annoying right now
